//
// Generated file, do not edit! Created by nedtool 4.6 from sd.msg.
//

#ifndef _SD_M_H_
#define _SD_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>sd.msg:16</tt> by nedtool.
 * <pre>
 * packet SrcPacket
 * {
 *     int src;
 *     int dest;
 * }
 * </pre>
 */
class SrcPacket : public ::cPacket
{
  protected:
    int src_var;
    int dest_var;

  private:
    void copy(const SrcPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SrcPacket&);

  public:
    SrcPacket(const char *name=NULL, int kind=0);
    SrcPacket(const SrcPacket& other);
    virtual ~SrcPacket();
    SrcPacket& operator=(const SrcPacket& other);
    virtual SrcPacket *dup() const {return new SrcPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSrc() const;
    virtual void setSrc(int src);
    virtual int getDest() const;
    virtual void setDest(int dest);
};

inline void doPacking(cCommBuffer *b, SrcPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, SrcPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _SD_M_H_

